api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


from api.views import (EventDetailsView, CreateEventView,
                       UpdateEventView, DeleteEventView)

app_name = 'api'

schema_view = get_schema_view(
   openapi.Info(
      title="Afisha|API docs",
      default_version='v1',
      description="API description",
      terms_of_service="https://www.google.com/policies/terms/"
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="docs"),
    path("auth/", include("djoser.urls")),
    path("auth/jwt/", include("djoser.urls.jwt")),

    path('event/<pk>', EventDetailsView.as_view(), name='event_details'),

    path('create/', CreateEventView.as_view(), name='create'),
    path('update/<pk>', UpdateEventView.as_view(), name='update'),
    path('delete/<pk>', DeleteEventView.as_view(), name='delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from events.views import EventPage, CategoryPage, SearchEvents

app_name = 'events'


urlpatterns = [
    path('event/<pk>', EventPage.as_view(), name='event'),
    path('category/<pk>', CategoryPage.as_view(), name='category'),
    path('search/', SearchEvents.as_view(), name='search')
    
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import LoginUser, LogoutUser, UserAccount, RegistrationUser

app_name = 'users'


urlpatterns = [
    path('login', LoginUser.as_view(), name='login'),
    path('logout', LogoutUser.as_view(), name='logout'),
    path('registration/', RegistrationUser.as_view(), name='registration'),
    
    path('account/<pk>', UserAccount.as_view(), name='account'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from users.managers import CustomManager
from django.contrib.auth import get_user_model

from django.utils.translation import ugettext as _
from django.core.validators import MaxValueValidator, MinValueValidator

from events.models import Event


# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)

    first_name = models.CharField(_('first name'), max_length=200, blank=True)
    last_name = models.CharField(_('last name'), max_length=200, blank=True)
    email = models.EmailField(_('email address'), max_length=200, blank=False, unique=True)
    
    date_created = models.DateTimeField(_("date joined"), auto_now_add=True)
    is_active = models.BooleanField(_("active"), default=True)
    is_staff = models.BooleanField(_("staff status"), default=False)
    is_superuser = models.BooleanField(_("superuser status"), default=False)

    is_admin = models.BooleanField(_("admin status"), default=False)
    is_editor = models.BooleanField(_("editor status"), default=False)
    is_reader = models.BooleanField(_("reader status"), default=False)

    favorite_events = models.ManyToManyField(to='events.Event', related_name='favorites', null=True, blank=True)

    objects = CustomManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email


class Order(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)

    customer = models.ForeignKey(to='users.CustomUser', related_name='customer',
                                 on_delete=models.CASCADE, null=False)
    event = models.ForeignKey(to='events.Event', related_name='event',
                              on_delete=models.RESTRICT, null=False)

    tickets_amount = models.IntegerField(blank=False, default=1,
                                         validators=[MaxValueValidator(20), MinValueValidator(1)])

    def total_cost(self):
        return self.event.price * self.tickets_amount

    def __str__(self):
        return f'{self.event}, {self.date_created}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, EmailField
from users.models import CustomUser


class RegistrationUserForm(UserCreationForm):
    email = EmailField(max_length=200, help_text="Registration without email is not possible!")

    class Meta:
        model = CustomUser
        fields = ['email', 'password1', 'password2']

users/views.py
from django.shortcuts import render
from events.models import Event
from django.views.generic import TemplateView, UpdateView, ListView, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from users.forms import RegistrationUserForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, authenticate


# Create your views here.
class LoginUser(LoginView):
    template_name = 'registration/login.html'
    success_url = reverse_lazy('index')

    
class LogoutUser(LogoutView):
    template_name = 'registration/logout.html'


class RegistrationUser(CreateView):
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('index')
    form_class = RegistrationUserForm
    
    def form_valid(self, form):
        self.object = form.save(commit=True)
        self.object.is_active = True
        self.object.save()

        user = authenticate(email=self.request.POST['email'],
                            password=self.request.POST['password1'])
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        return super().form_valid(form)


class UserAccount(ListView):
    template_name = 'user_account.html'
    queryset = Event.objects.all().order_by('date_time')
    context_object_name = "favorite_events"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserAccount, self).get_context_data(**kwargs)

        favorite_events = self.request.user.favorite_events
        context['favorite_events'] = favorite_events
        
        return context

users/templates/user_account.html
{% extends "index.html" %}

{% block header %}
  <header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}"><h2><em>Afisha</em> Events</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li><a class="nav-link" href="{% url 'users:logout' %}">Logout</i></a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
{% endblock %}


{% block content %}
    <div class="page-heading products-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h2>welcome!</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="team-members">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
                <h2><strong>Events you ♥:</strong></h2>
            </div>
          </div>
          {% for event_item in favorite_events.all %}
            <div class="col-lg-4 col-md-4 all des">
              <div class="product-item">
                <a href="{% url 'events:event' pk=event_item.id %}"><img src="{{ event_item.media.url }}" height="400" width="200" alt=""></a>
                <div class="down-content">
                  <a href="{% url 'events:event' pk=event_item.id %}"><h4>{{ event_item.name }}</h4></a>
                  <h6>{{ event_item.price }}</h6>
                  <p>{{ event_item.description }}</p>
                  <span>{{ event_item.date_time }}</span>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}