api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


from api.views import (EventDetailsView, CreateEventView,
                       UpdateEventView, DeleteEventView)

app_name = 'api'

schema_view = get_schema_view(
   openapi.Info(
      title="Afisha|API docs",
      default_version='v1',
      description="API description",
      terms_of_service="https://www.google.com/policies/terms/"
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="docs"),
    path("auth/", include("djoser.urls")),
    path("auth/jwt/", include("djoser.urls.jwt")),

    path('event/<pk>', EventDetailsView.as_view(), name='event_details'),

    path('create/', CreateEventView.as_view(), name='create'),
    path('update/<pk>', UpdateEventView.as_view(), name='update'),
    path('delete/<pk>', DeleteEventView.as_view(), name='delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from events.views import EventPage, CategoryPage, SearchEvents

app_name = 'events'


urlpatterns = [
    path('event/<pk>', EventPage.as_view(), name='event'),
    path('category/<pk>', CategoryPage.as_view(), name='category'),
    path('search/', SearchEvents.as_view(), name='search')
    
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import LoginUser, LogoutUser, UserAccount, RegistrationUser

app_name = 'users'


urlpatterns = [
    path('login', LoginUser.as_view(), name='login'),
    path('logout', LogoutUser.as_view(), name='logout'),
    path('registration/', RegistrationUser.as_view(), name='registration'),
    
    path('account/<pk>', UserAccount.as_view(), name='account'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.utils.translation import ugettext as _
import uuid
import random
import datetime
from django.utils import timezone

from djmoney.models.fields import MoneyField
from django.core.validators import MaxValueValidator, MinValueValidator

WEEK_IN_SECONDS = 604800
YEAR_IN_SECONDS = 31449600
DEFAULT_DESCRIPTION = 'Lorem ipsum dolor sit amet, consectetur adipisic elit. Sed voluptate nihil eumester ' \
                      'consectetur similiqu consectetur. Lorem ipsum dolor sit amet, consectetur adipisic ' \
                      'elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti.'


# Create your models here.
class Event(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)

    name = models.CharField(max_length=200, blank=False, null=False, default='event1')
    description = models.TextField(max_length=1000, blank=True, default=DEFAULT_DESCRIPTION)
    media = models.ImageField(upload_to='event_images', null=True, blank=True,
                              default='event_images/default.jpeg')
    
    date_time = models.DateTimeField(blank=False)
    price = MoneyField(max_digits=10, decimal_places=2, null=True, default_currency='UAH')
    tickets_amount = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1)])

    location = models.ForeignKey(to='events.Location', related_name='location',
                                 on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(to='events.Category', related_name='category', 
                                 on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

    @classmethod
    def generate_events(cls, count):
        EVENT_NAMES = ['Coldplay', 'Inhaler', 'Luna', 'Woodkid', 'Splin', 'Contemporary Ukrainian photography',
                       'Non-stop Painting', 'Amazing Stories of Crimea', 'Instant time exhibition',
                       'Interior of the Year 2022', 'Sziget 2022', 'Lollapalooza Stockholm 2022',
                       'Rock Werchter 2022', 'Atlas Weekend', 'Underground Standup', 'Improv Live Show',]
        for _ in range(count):
            new_event = cls(
                name=random.choice(EVENT_NAMES),
                date_time=timezone.now() + datetime.timedelta(seconds=random.randint(WEEK_IN_SECONDS, 
                                                                                     YEAR_IN_SECONDS)),
                price=random.randrange(60, 20000, 1),
                tickets_amount=random.randint(2, 500),
                location_id=Category.get_random())  # FOREIGN KEY constraint failed
        # new_event.save()
            

class Category(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    
    name = models.CharField(max_length=200, blank=False, null=False, default='events_set1')
    description = models.TextField(max_length=1000, blank=True, default=DEFAULT_DESCRIPTION)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return self.name
    
    @classmethod
    def get_random(cls):
        categories_list = list(Category.objects.all())
        random_category = random.choice(categories_list)
        return random_category

        # uuids = cls.objects.values_list('id', flat=True)
        # uuid_random = random.choice(uuids)
        # return str(uuid_random)


class Location(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)

    name = models.CharField(max_length=200, blank=False, null=False, default='location1')
    comment = models.CharField(max_length=300, blank=True)
    image = models.ImageField(upload_to='event_images', null=True, blank=True)

    city = models.CharField(max_length=100, blank=False)
    street = models.CharField(max_length=200, blank=True)
    house_number = models.CharField(max_length=200, blank=True)  # not IntField but CharField for cases as '16/a'

    def __str__(self):
        return self.name

events/views.py
from django.shortcuts import render
from django.db.models import Q

from django.views.generic import TemplateView, ListView, DetailView
from events.models import Event, Category


# Create your views here.
class IndexPage(ListView):
    template_name = 'index.html'
    queryset = Event.objects.all().order_by('date_time')
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(IndexPage, self).get_context_data(**kwargs)
        context['categories_list'] = Category.objects.all()

        return context


class EventPage(ListView):
    template_name = 'event_details.html'
    queryset = Event.objects.all().order_by('date_time')
    context_object_name = "events_list"
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super(EventPage, self).get_context_data(**kwargs)

        event = Event.objects.get(id=self.kwargs.get("pk"))
        context['event'] = event

        if event.category:
            self.queryset = Event.objects.filter(category_id=event.category_id)

        context['categories_list'] = Category.objects.all()
        context['events_list'] = self.queryset.exclude(id=event.id)

        return context


class SearchEvents(ListView):
    template_name = 'search_events.html'
    queryset = Event.objects.all().order_by('date_time')
    context_object_name = "events_list"
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super(SearchEvents, self).get_context_data(**kwargs)

        search_text = self.request.GET.get('search')
        events = Event.objects.all()
        text_fields = ["name", "description", "location__name", 'location__city', 'category__name']

        if search_text:
            or_filter = Q()
            for field in text_fields:
                or_filter |= Q(**{f"{field}__icontains": search_text})
            events = Event.objects.filter(or_filter)

        context['search_text'] = search_text
        context['events_list'] = events
        context['categories_list'] = Category.objects.all()

        return context


class CategoryPage(ListView):
    template_name = 'category_details.html'
    queryset = Event.objects.all().order_by('date_time')
    context_object_name = "events_list"
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super(CategoryPage, self).get_context_data(**kwargs)

        category = Category.objects.get(id=self.kwargs.get('pk'))

        context['category'] = category
        context['events_list'] = Event.objects.filter(category_id=category.id).order_by('date_time')
        context['categories_list'] = Category.objects.all()
        return context


class ContactsPage(TemplateView):
    template_name = 'contact.html'
    extra_context = {'categories_list': Category.objects.all()}

events/templates/category_details.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
    <div class="page-heading products-heading header-text">
    </div>

    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2><strong>{{ category.name }}</strong></h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image" >
              <h7>{{ category.description }}</h7>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="team-members">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Category events:</h2>
            </div>
          </div>
          {% for event_item in events_list %}
            <div class="col-lg-4 col-md-4 all des">
              <div class="product-item">
                <a href="{% url 'events:event' pk=event_item.id %}"><img src="{{ event_item.media.url }}" height="400" width="200" alt=""></a>
                <div class="down-content">
                  <a href="{% url 'events:event' pk=event_item.id %}"><h4>{{ event_item.name }}</h4></a>
                  <h6>{{ event_item.price }}</h6>
                  <p>{{ event_item.description }}</p>
                  <span>{{ event_item.date_time }}</span>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

events/templates/contact.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <!-- Page Content -->
    <div class="page-heading contact-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>contact us</h4>
              <h2>let’s stay in touch</h2>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="find-us">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Our Office</h2>
            </div>
          </div>
          <div class="col-md-8">

          <div id="map">
            <img src="{% static 'images/office_image.jpeg' %}" width="80%" height="330px" frameborder="0" style="border:0" allowfullscreen>
          </div>

          </div>
          <div class="col-md-4">
            <div class="left-content">
              <h4>About us</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisic elit. Sed voluptate nihil eumester consectetur
                  similiqu consectetur.<br><br>Lorem ipsum dolor sit amet, consectetur adipisic elit. Et, consequuntur,
                  modi mollitia corporis ipsa voluptate corrupti.</p>
                  <h4>Our contacts:</h4>
              <ul class="social-icons">
                <li><a href="https://t.me/kolodezhnaya" target="_blank"><i class="fa  fa-paper-plane"></i></a></li>
                <li><a href="https://www.instagram.com/nastya.kolodezhnaya/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://www.linkedin.com/in/anastasia-kolodezhnaya-95aa50197/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="https://github.com/NastyaKolodezhnaya" target="_blank"><i class="fa fa-github"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

events/templates/event_details.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
    <div class="page-heading products-heading header-text">
    </div>

    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2><strong>{{ event.name }}</strong></h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image" >
              <img src="{{ event.media.url }}" alt="event-image" width="30%">
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <ul class="social-icons">
                <h4>{{ event.date_time.date }}, {{ event.date_time.time }}</h4>
                <h4>{{ event.location }}</h4>
                <h4>{{ event.price }}</h4>
              </ul>
              <p>{{ event.description }}</p>
            </div>
<!--            {% if user.is_authenticated %}-->
<!--              <form action="{% url 'users:account' pk=user.id %}" method="post">-->
<!--                {% csrf_token %}-->
<!--                <input type="hidden" pk="{{ user.id }}" />-->
<!--                <button type="submit" class="btn btn-danger btn-lg">Add to favorites ♥</button>-->
<!--              </form>-->
<!--            {% else %}-->
<!--              <form action="{% url 'users:login' %}">-->
<!--                <button type="submit" class="btn btn-danger btn-lg">Add to favorites ♥</button>-->
<!--              </form>-->
<!--            {% endif %}-->
          </div>
        </div>
      </div>
    </div>

    
    <div class="team-members">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Similar events</h2>
            </div>
          </div>
          {% for event_item in events_list %}
            <div class="col-lg-4 col-md-4 all des">
              <div class="product-item">
                <a href="{% url 'events:event' pk=event_item.id %}"><img src="{{ event_item.media.url }}" height="400" width="200" alt=""></a>
                <div class="down-content">
                  <a href="{% url 'events:event' pk=event_item.id %}"><h4>{{ event_item.name }}</h4></a>
                  <h6>{{ event_item.price }}</h6>
                  <p>{{ event_item.description }}</p>
                  <span>{{ event_item.date_time }}</span>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}



events/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Afisha | Events</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing
https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/util.css' %}">


  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    {% block header %}
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}"><h2><em>Afisha</em> Events</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

<!--      Categories buttons-->
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              {% for category in categories_list %}
              <li>
                <a class="nav-link" href="{% url 'events:category' pk=category.id %}">{{ category.name }}
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              {% endfor %}

<!--          Search bar-->
              <li>
                <form method="GET" class="form-inline tm-mb-80 tm-search-form" action="{% url 'events:search' %}">
                <div class="p-1 bg-light rounded rounded-pill shadow-sm mb-4">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <button id="button-addon" type="submit" class="btn btn-link text-danger"><i class="fa fa-search"></i></button>
                    </div>
                    <input id="search" type="text" name="search" placeholder="Search.." aria-describedby="button-addon2" class="form-control border-0 bg-light">
                  </div>
                </div>
              </form>
              </li>

              {% if user.is_authenticated %}
                {% if user.first_name %}
                  <li><a class="nav-link" href="{% url 'users:account' pk=user.id %}">{{ user.first_name }}</i></a></li>
                {% else %}
                  <li><a class="nav-link" href="{% url 'users:account' pk=user.id %}">Account</i></a></li>
                {% endif %}

              {% else %}
                <li><a class="nav-link" href="{% url 'users:login' %}">Login</i></a></li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
    </header>
    {% endblock %}

    <!-- Page Content -->
    {% block content %}
    <div class="page-heading products-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>have fun!</h4>
              <h2>all of the events in your city</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" onclick="filterSelection('all')">All events</li>
                  {% for category in categories_list %}
                    <li data-filter="">{{ category.name }}</li>
                  {% endfor %}
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                  {% for event in event_list %}
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <a href="{% url 'events:event' pk=event.id %}"><img src="{{ event.media.url }}" alt="" height="400" width="200"></a>
                        <div class="down-content">
                          <a href="{% url 'events:event' pk=event.id %}"><h4>{{ event.name }}</h4></a>
                          <h6>{{ event.price }}</h6>
                          <p>{{ event.description }}</p>
                          <span>{{ event.date_time }}</span>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
          </div>

<!--      Pagination-->
          <div class="col-md-12">
            <ul class="pages">
              {% for page_number in page_obj.paginator.page_range %}
                {% if page_number == page_obj.number %}
                  <li class="active"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% else %}
                  <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <p>Copyright &copy; 2021 Anastasiia Kolodezhnaya
            
                - <a href="{% url 'contacts' %}">Contacts</a><br>
                Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>

events/templates/search_events.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
    <div class="page-heading products-heading header-text">
    </div>
    
    <div class="team-members">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
                {% if events_list %}
                    <h2><strong>Search by '{{ search_text }}':</strong></h2>
                {% else %}
                    <h2><strong>Unfortunately, no such results :(</strong></h2>
                {% endif %}
            </div>
          </div>
          {% for event_item in events_list %}
            <div class="col-lg-4 col-md-4 all des">
              <div class="product-item">
                <a href="{% url 'events:event' pk=event_item.id %}"><img src="{{ event_item.media.url }}" height="400" width="200" alt=""></a>
                <div class="down-content">
                  <a href="{% url 'events:event' pk=event_item.id %}"><h4>{{ event_item.name }}</h4></a>
                  <h6>{{ event_item.price }}</h6>
                  <p>{{ event_item.description }}</p>
                  <span>{{ event_item.date_time }}</span>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}